Repository encode/django-rest-framework, pull requests merged in 2018-10, with the labels that each got.

#6145 Removing (potential erroneous) confusing dot "`.`method()"
  tutorial/4-authentication-and-permissions/index.html
Labels: Documentation

#6137 Remove dot character from "pagination_class"
  docs/api-guide/pagination.md
Labels: Documentation

#5753 permissions: Allow permissions to be composed
  docs/api-guide/permissions.md
  rest_framework/permissions.py
  tests/test_permissions.py
Labels: Enhancement

#6060 Feature/action docs sections
  docs/topics/documenting-your-api.md
  rest_framework/schemas/inspectors.py
  tests/test_schemas.py
Labels: Schema Generation
