Repository encode/django-rest-framework, pull requests merged in 2022-11, with the labels that each got.

#8727 Fixes instance check in ListSerializer.to_representation (#8726)
  rest_framework/serializers.py
  tests/models.py
  tests/test_serializer_lists.py
Labels: Bug

#8362 Added pagination settings test case
  tests/test_settings.py
Labels: testcase

#8590 Update 6-viewsets-and-routers.md
  docs/tutorial/6-viewsets-and-routers.md
Labels: Documentation

#8429 Represent SafeString as plain string on schema rendering.
  rest_framework/renderers.py
  tests/schemas/test_openapi.py
Labels: Bug

#8017 Fix OpenAPI operation name plural appropriately
  requirements/requirements-optionals.txt
  rest_framework/schemas/openapi.py
  tests/schemas/test_openapi.py
Labels: Schema Generation, stale

#8042 Properly handle OverflowError in DurationField deserialization
  rest_framework/fields.py
  tests/test_fields.py
Labels: Bug

#8713 Implemented Verbose Name Translation for TokenProxy
  rest_framework/authtoken/migrations/0004_alter_tokenproxy_options.py
  rest_framework/authtoken/models.py
Labels: Bug, Cleanup

#8778 Register Django urls
  docs/tutorial/quickstart.md
Labels: Documentation
