Repository encode/django-rest-framework, pull requests merged in 2022-12, with the labels that each got.

#8779 Fix bug in validators documentation
  docs/api-guide/validators.md
Labels: Documentation

#8783 Remove a bit of inline CSS. Add CSP nonce where it might be required and is available.
  rest_framework/static/rest_framework/css/bootstrap-tweaks.css
  rest_framework/templates/rest_framework/base.html
  rest_framework/templates/rest_framework/pagination/numbers.html
Labels: Enhancement

#6423 Handle Django's ValidationErrors in ListField
  rest_framework/fields.py
  tests/test_fields.py
Labels: Bug

#8614 Fix BooleanField's allow_null behavior
  rest_framework/fields.py
  tests/test_fields.py
Labels: Bug, Cleanup

#8315 Use PrimaryKeyRelatedField pkfield in openapi
  rest_framework/schemas/openapi.py
  tests/schemas/test_openapi.py
Labels: Bug

#8438 raise ImproperlyConfigured exception if `basename` is not unique
  rest_framework/routers.py
  tests/test_routers.py
Labels: Bug, Enhancement
