Repository encode/django-rest-framework, pull requests merged in 2023-05, with the labels that each got.

#8954 fix: fallback on CursorPagination ordering if unset on the view
  rest_framework/pagination.py
  tests/test_pagination.py
Labels: Bug

#8968 Fix mapping for choice values
  rest_framework/fields.py
  tests/test_fields.py
Labels: Enhancement

#8001 Make set_value a method within `Serializer`
  rest_framework/fields.py
  rest_framework/serializers.py
  tests/test_serializer.py
Labels: Cleanup

#8979 Fix validation for ListSerializer
  rest_framework/serializers.py
  tests/test_serializer.py
Labels: Bug
