Repository encode/django-rest-framework, pull requests merged in 2023-07, with the labels that each got.

#9023 Fix: SearchFilter renders search field with invalid value
  rest_framework/filters.py
  tests/test_filters.py
Labels: Bug

#8955 Fix choices in ChoiceField to support IntEnum
  rest_framework/fields.py
  tests/test_fields.py
Labels: Bug, Enhancement

#9049 Fix: Pagination response schemas.
  rest_framework/pagination.py
  tests/test_pagination.py
Labels: Bug

#8035 Allow to override child.run_validation call in ListSerializer
  rest_framework/serializers.py
  tests/test_serializer_lists.py
Labels: Enhancement
