Repository encode/django-rest-framework, pull requests merged in 2023-04, with the labels that each got.

#8922 Handle Nested Relation in SlugRelatedField when many=False
  rest_framework/relations.py
  tests/test_relations.py
  tests/utils.py
Labels: Bug

#8934 Add username search field for TokenAdmin (#8927)
  rest_framework/authtoken/admin.py
Labels: Enhancement

#8924 Use ZoneInfo as primary source of timezone data
  rest_framework/fields.py
  rest_framework/utils/timezone.py
  setup.py
  tests/test_fields.py
Labels: Enhancement

#8912 Ensure CursorPagination respects nulls in the ordering field
  rest_framework/pagination.py
  tests/test_pagination.py
Labels: Bug, Enhancement
