Repository encode/django-rest-framework, pull requests merged in 2023-08, with the labels that each got.

#9030 Propagate 'default' from model_field to serializer field.
  docs/api-guide/fields.md
  rest_framework/metadata.py
  rest_framework/utils/field_mapping.py
  tests/test_metadata.py
  tests/test_model_serializer.py
Labels: Bug, Enhancement

#7563 Partial serializer should not have required fields (OpenAPI)
  rest_framework/schemas/openapi.py
  tests/schemas/test_openapi.py
Labels: Schema Generation, stale

#6967 Add docs validation to release process
  .github/workflows/main.yml
  docs/community/project-management.md
  requirements/requirements-documentation.txt
Labels: Documentation, Release

#9055 Add note for HiddenField behavior
  docs/api-guide/fields.md
  docs/api-guide/validators.md
Labels: Documentation

#9066 Use str as default path converter
  rest_framework/routers.py
  tests/test_routers.py
Labels: Bug, Enhancement
