Repository encode/django-rest-framework, pull requests merged in 2025-08, with the labels that each got.

#9749 Turkish Translation updates
  rest_framework/locale/tr/LC_MESSAGES/django.mo
  rest_framework/locale/tr/LC_MESSAGES/django.po
Labels: Translations

#9758 Fix a number of broken links in the docs
  docs/api-guide/schemas.md
  docs/community/3.1-announcement.md
  docs/community/3.3-announcement.md
  docs/community/3.4-announcement.md
  docs/community/3.5-announcement.md
  docs/community/third-party-packages.md
Labels: Documentation

#9717 add a new third-party package in serializers.md
  docs/api-guide/serializers.md
  docs/community/third-party-packages.md
Labels: Documentation

#9754 Prevent small risk of `Token` overwrite
  rest_framework/authtoken/models.py
  tests/test_authtoken.py
Labels: Bug

#9759 Automate docs deployment
  .github/workflows/mkdocs-deploy.yml
Labels: Process

#9380 Add documentation about how to transform factory request to DRF request
  docs/api-guide/testing.md
  tests/test_testing.py
Labels: Documentation
